[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

addopts =
    -v
    --strict-markers
    --alluredir=artifacts/allure-results
    --reruns=1
    --reruns-delay=2

markers =
    smoke: Critical functionality
    sanity: Quick validation after a build
    regression: Full regression suite
    mock: WireMock test suite